---
- hosts: all
  connection: ssh
  gather_facts: True

  tasks:
   - name: disable SELinux on reboot
     selinux:
       state: disabled

   - name: disable firewalld
     systemd:
       name: firewalld
       state: stopped
       enabled: no

   - name: Generate /etc/hosts file
     template:
       src=hosts.j2
       dest=/etc/hosts

- hosts: master,worker
  connection: ssh
  gather_facts: True

  tasks:
   - name: modprebe br_netfilter
     command: modprobe br_netfilter

   - name: ensure net.ipv4.ip_forward is set to 1
     sysctl: name=net.ipv4.ip_forward value=1 state=present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: disable Swap
     command: swapoff -a